# Generated by Django 3.2.19 on 2023-06-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
