# Generated by Django 3.2.19 on 2023-06-10 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('reviews', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.review'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'comment'), ('owner', 'review'), ('owner', 'post')},
        ),
    ]
